# Generated by Django 3.2.25 on 2024-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240610_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
