# Generated by Django 3.2.25 on 2024-06-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
